version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-dev:1.0.0
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gjsx.rule=Host(`gjsx.fltngmmth.com`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=namecheap
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8085

        # - traefik.http.routers.fm-jsxgi.rule=Host(`${PROJECT1:-noah.fltngmmth.com}`)
        # - traefik.http.routers.fm-jsxgi.entrypoints=http,https
        # - traefik.http.routers.fm-jsxgi.middlewares=https-redirect
        # - traefik.http.routers.fm-jsxgi.service=fm-jsxgi
        # - traefik.http.routers.fm-jsxgi.tls=true
        # - traefik.http.routers.fm-jsxgi.tls.certresolver=namecheap
        # - traefik.http.services.fm-jsxgi.loadbalancer.server.port=8086
    networks:
      - public
    volumes:
      - compiled:/home/app/_compiled
      - assets:/home/app/assets
      - lib:/home/app/lib
volumes:
  lib:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/lib
  compiled:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/_compiled
  assets:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/assets

networks:
  public:
    external: true

