version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-dev:${VERSION:-1.0.0}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gjsx.rule=Host(`gjsx.fltngmmth.com`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=namecheap
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8086
        - traefik.http.routers.gun-relay.rule=Host(`peer-relay-3369111.fltngmmth.com`)
        - traefik.http.routers.gun-relay.entrypoints=http,https
        - traefik.http.routers.gun-relay.middlewares=https-redirect
        - traefik.http.routers.gun-relay.service=gun-relay
        - traefik.http.routers.gun-relay.tls=true
        - traefik.http.routers.gun-relay.tls.certresolver=namecheap
        - traefik.http.services.gun-relay.loadbalancer.server.port=8087
    networks:
      - public
      - edge 
      - socket-proxy
    volumes:
      - compiled:/home/app/_compiled    
      - assets:/home/app/assets
      - proxyserver:/home/app/proxyserver
      - datastore_gundb:/home/app/datastore_gundb
      - logs:/var/log
volumes:
  datastore_gundb:
    driver: local-persist
    driver_opts:
      mountpoint: $PROJECT_DIR/datastore_gundb
  proxyserver:
    driver: local-persist
    driver_opts:
      mountpoint: $PROJECT_DIR/proxyserver
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: $PROJECT_DIR/log
  compiled:
    driver: local-persist
    driver_opts:
      mountpoint: $PROJECT_DIR/_compiled
  assets:
    driver: local-persist
    driver_opts:
      mountpoint: $PROJECT_DIR/assets

networks:
  edge:
    external: true
  public:
    external: true
  socket-proxy:
    external: true

