version: "3.8"

services:
  broadway:
    image: bresnow/gjsx-broadway-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 39660:8085
    volumes:
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/lib:/home/app/lib
      - ${PWD}/assets:/home/app/assets

