version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-broadway:alpine-3.16-${VERSION:-v3.3.3}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gjsx.rule=Host(`${PROJECT:-gjsx-broadway.fltngmmth.com}`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=namecheap
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8085
    networks:
      - public
    volumes:
      - ${PWD}/src:/home/app/src
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/types:/home/app/types
      - ${PWD}/esbuild.mjs:/home/app/esbuild.mjs
      - ${PWD}/gtk4-template.ui:/home/app/gtk4-template.ui
      - ${PWD}/package.json:/home/app/package.json
      - ${PWD}/tsconfig.json:/home/app/tsconfig.json
      - ${PWD}/startapp.sh:/startapp.sh
networks:
  public:
    external: true

