version: "3.8"

services:
  broadway:
    image: bresnow/gjsx-broadway
    build:
      context: .
      target: broadway
    ports:
      - 39660:8085
    volumes:
      - ${PWD}/src:/home/app/src
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/types:/home/app/types
      - ${PWD}/esbuild.mjs:/home/app/esbuild.mjs
      - ${PWD}/gtk4-template.ui:/home/app/gtk4-template.ui
      - ${PWD}/package.json:/home/app/package.json
      - ${PWD}/tsconfig.json:/home/app/tsconfig.json
