version: "3.9"

services:
  gjsx_dev1:
    image: bresnow/gjsx-dev:${VERSION:-1.2.2}
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.swarm.node.subdomain == ${NODELABEL_VALUE:-gpu.cnxt369}
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gsx-${NUM-0}.rule=Host(`${DOMAIN:-cnxt.gpu.fltngmmth.com}`)
        - traefik.http.routers.fm-gsx-${NUM-0}.entrypoints=http,https
        - traefik.http.routers.fm-gsx-${NUM-0}.middlewares=https-redirect
        - traefik.http.routers.fm-gsx-${NUM-0}.service=fm-gsx-${NUM-0}
        - traefik.http.routers.fm-gsx-${NUM-0}.tls=true
        - traefik.http.routers.fm-gsx-${NUM-0}.tls.certresolver=namecheap
        - traefik.http.services.fm-gsx-${NUM-0}.loadbalancer.server.port=8086
#---#---#0---#---# ---#---#
        - traefik.http.routers.gun-relay.rule=Host(`{PEERDOMAIN:-peer.gpu.fltngmmth.com}`)
        - traefik.http.routers.gun-relay-${NUM-0}.entrypoints=http,https
        - traefik.http.routers.gun-relay-${NUM-0}.middlewares=https-redirect
        - traefik.http.routers.gun-relay-${NUM-0}.service=gun-relay-${NUM-0}
        - traefik.http.routers.gun-relay-${NUM-0}.tls=true
        - traefik.http.routers.gun-relay-${NUM-0}.tls.certresolver=namecheap
        - traefik.http.services.gun-relay-${NUM-0}.loadbalancer.server.port=8087
    networks:
      - public
      - edge 
      - socket-proxy
    volumes:
      - compiled:/home/app/_compiled    
      - assets:/home/app/assets
      - proxyserver:/home/app/proxyserver
      - datastore_gundb1:/home/app/datastore_gundb
      - logs:/var/log/gjsx
volumes:
  datastore_gundb1:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/datastore_gundb1
  datastore_gundb:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/datastore_gundb
  proxyserver:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/proxyserver
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/log
  compiled:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/_compiled
  assets:
    driver: local-persist
    driver_opts:
      mountpoint: ${DIRECTORY:-/home/administrator/com.fileshare.gpu.cnxt}/assets

networks:
  edge:
    external: true
  public:
    external: true
  socket-proxy:
    external: true

