version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-broadway
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gjsx.rule=Host(`${PROJECT:-gjsx-broadway.fltngmmth.com}`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=namecheap
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8085
    networks:
      - public
    volumes:
      - app:/home/app
volumes:
  app:
    driver: local-persist
    driver_opts:
      mountpoint: ${HOME}/fltngmmth/relay

networks:
  public:
    external: true

