version: '3.8'

services:

  broadway:
    image: bresnow/broadway-proxy:alpine-3.16-${VERSION:-v1.1.1}
    build: 
      context: .
      dockerfile: Dockerfile
      target: broadway-proxy
    ports:
      - 39660:8085
    volumes:
      - ${PWD}/src:/config/app/src
      - ${PWD}/_compiled:/config/app/_compiled
      - ${PWD}/types:/config/app/types
        # - ${PWD}/startapp.sh:/startapp.sh
      - ${PWD}/esbuild.mjs:/config/app/esbuild.mjs
      - ${PWD}/package.json:/config/app/package.json
      - ${PWD}/tsconfig.json:/config/app/tsconfig.json
    environment:
      KEEP_APP_RUNNING: 0
  # baseimage:
  #   image: bresnow/nodegtk-broadway-baseimage:alpine-3.15-${VERSION:-v1.0.3}
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
    
