version: "3.8"
services:
  gtk4_dev:
    image: bresnow/gjsx-core:${VERSION:-1.8.6}
    build:
      context: .
      dockerfile: Dockerfile
      target: gjsx-gtk4
  remix-watch:
    image: bresnow/gjsx-dev:${VERSION:-1.8.6}
    build:
      context: .
      dockerfile: Dockerfile
      target: remix-watch
  front_proxy:
    image: bresnow/gjsx-proxy:${VERSION:-1.8.6}
    build:
      context: .
      dockerfile: Dockerfile
      target: front-proxy