version: '3.8'

services:

  gjs:
    build: 
      context: .
      dockerfile: Dockerfile
      target: broadway-proxy
    ports:
      - 8086:8086
      - 8085:8085
    volumes:
      - ${PWD}/packages:/config

  # baseimage:
  #   image: bresnow/nodegtk-broadway-baseimage:alpine-3.15-${VERSION:-v1.0.3}
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
    