version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-dev:1.0.0
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.fm-gjsx.rule=Host(`${SUBDOMAIN:-gjsx}.fltngmmth.com`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=namecheap
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8086
    networks:
      - public
      - edge 
      - socket-proxy
    volumes:
      - compiled:/home/app/_compiled    
      - assets:/home/app/assets
      - proxyserver:/home/app/proxyserver
      - logs:/var/log
volumes:
  proxyserver:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/proxyserver
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/log
  compiled:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/_compiled
  assets:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/assets

networks:
  edge:
    external: true
  public:
    external: true
  socket-proxy:
    external: true

