version: "3.8"

services:
  broadway:
    image: bresnow/gjsx-broadway-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 39660:8085
    volumes:
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/lib:/home/app/lib
      - ${PWD}/assets:/home/app/assets
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.constraint-label=public
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.rule=Host(`${PROJECT:-gjsx-broadway.fltngmmth.com}`)
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.entrypoints=http,https
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.middlewares=https-redirect
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.service=fm-gjsx-${NUMBER:-0}
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.tls=true
      - traefik.http.routers.fm-gjsx-${NUMBER:-0}.tls.certresolver=namecheap
      - traefik.http.services.fm-gjsx-${NUMBER:-0}.loadbalancer.server.port=8085
networks:
  public:
    external: true

