version: "3.8"

services:
  broadway:
    image: bresnow/gjsx-broadway:${VERSION?-SET VERSION NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
      target: gjsx-app
    ports:
      - 8087:8087 # Relay Server
      - 8086:8086 # Broadway
    volumes:
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/lib:/home/app/lib
      - ${PWD}/assets:/home/app/assets
      - ${PWD}/proxyserver:/home/app/proxyserver
      - ${PWD}/datastore_gundb:/home/app/datastore_gundb
      - ${PWD}/node_modules:/home/app/node_modules
      - ${PWD}/log:/var/log/gjsx
