version: "3.8"

services:
  broadway:
    image: bresnow/gjsx-dev:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: broadway-app
    ports:
      - 3985:8085
      # - 8086:8086
    volumes:
      - ${PWD}/_compiled:/home/app/_compiled
      - ${PWD}/lib:/home/app/lib
      - ${PWD}/assets:/home/app/assets
      - ${PWD}/log:/var/log
