version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-dev:${VERSION:-1.0.0}
    deploy:
      placement:
        constraints:
          - node.role == manager
          # - node.labels.swarm.node.subdomain == gpu.cnxt369
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - traefik.http.routers.fm-gjsx.rule=Host(`cnxt.gpu.fltngmmth.com`)
        - traefik.http.routers.fm-gjsx.entrypoints=http,https
        # - traefik.http.routers.fm-gjsx.middlewares=https-redirect
        - traefik.http.routers.fm-gjsx.service=fm-gjsx
        - traefik.http.routers.fm-gjsx.tls=true
        - traefik.http.routers.fm-gjsx.tls.certresolver=letsencrypt
        - traefik.http.services.fm-gjsx.loadbalancer.server.port=8086
        - traefik.http.routers.gun-relay.rule=Host(`peer-relay.fltngmmth.com`)
        - traefik.http.routers.gun-relay.entrypoints=http,https
        # - traefik.http.routers.gun-relay.middlewares=https-redirect
        - traefik.http.routers.gun-relay.service=gun-relay
        - traefik.http.routers.gun-relay.tls=true
        - traefik.http.routers.gun-relay.tls.certresolver=letsencrypt
        - traefik.http.services.gun-relay.loadbalancer.server.port=8087
    networks:
      - traefik-net
    volumes:
      - compiled:/home/app/_compiled    
      - assets:/home/app/assets
      - proxyserver:/home/app/proxyserver
      - datastore_gundb:/home/app/datastore_gundb
      - logs:/var/log/gjsx
volumes:
  datastore_gundb:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/datastore_gundb
  proxyserver:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/proxyserver
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/log
  compiled:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/_compiled
  assets:
    driver: local-persist
    driver_opts:
      mountpoint: $PWD/assets

networks:
  traefik-net:
    external: true
  # socket-proxy:
  #   external: true

