version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-broadway:${VERSION:-1.3.1}
    deploy:
      placement:
        constraints:
          - node.role == manager
          # - node.labels.swarm.node.subdomain == gpu.cnxt369
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - traefik.http.routers.fm-gjsx-${ID:-001}.rule=Host(`${DOMAIN:-cnxt.gpu.fltngmmth.com}`)
        - traefik.http.routers.fm-gjsx-${ID:-001}.entrypoints=http,https
        - traefik.http.routers.fm-gjsx-${ID:-001}.service=fm-gjsx-${ID:-001}
        - traefik.http.routers.fm-gjsx-${ID:-001}.tls=true
        - traefik.http.routers.fm-gjsx-${ID:-001}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.fm-gjsx-${ID:-001}.loadbalancer.server.port=8086
        - traefik.http.routers.gun-relay-${ID:-001}.rule=Host(`${PEER:-peer-relay.fltngmmth.com}`)
        - traefik.http.routers.gun-relay-${ID:-001}.entrypoints=http,https
        - traefik.http.routers.gun-relay-${ID:-001}.service=gun-relay-${ID:-001}
        - traefik.http.routers.gun-relay-${ID:-001}.tls=true
        - traefik.http.routers.gun-relay-${ID:-001}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.gun-relay-${ID:-001}.loadbalancer.server.port=8087
    networks:
      - traefik-net
    volumes:
      - $PWD/_compiled:/home/app/_compiled    
      - $PWD/assets:/home/app/assets
      - $PWD/proxyserver:/home/app/proxyserver
      - $HOME/datastore_gundb-${ID:-001}:/home/app/datastore_gundb
      - $PWD/logs/id-${ID:-001}:/var/log/gjsx
      - /dev/dri/card0:/dev/dri/card0:rw
      - /dev/dri/renderD128:/dev/dri/renderD128:rw

# volumes:
#   datastore_gundb:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $PWD/datastore_gundb
#   proxyserver:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $PWD/proxyserver
#   logs:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $PWD/log
#   compiled:
#     driver: local-persist
#     driver_opts:
#       mountpoint: 
#   assets:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $PWD/assets

networks:
  traefik-net:
    external: true
  # socket-proxy:
  #   external: true

