version: "3.9"

services:
  gjsx_dev:
    image: bresnow/gjsx-dev:${VERSION:-latest}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - traefik.http.routers.proxy-${ID:-xdesk}.rule=Host(`${DOMAIN:-namspace.fltngmmth.com}`)
        - traefik.http.routers.proxy-${ID:-xdesk}.entrypoints=http,https
        - traefik.http.routers.proxy-${ID:-xdesk}.service=proxy-${ID:-xdesk}
        - traefik.http.routers.proxy-${ID:-xdesk}.tls=true
        - traefik.http.routers.proxy-${ID:-xdesk}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.proxy-${ID:-xdesk}.loadbalancer.server.port=8087
        - traefik.http.routers.gjsx-${ID:-xdesk}.rule=Host(`${INTERFACE_DOMAIN:-sys.product.fltngmmth.com}`)
        - traefik.http.routers.gjsx-${ID:-xdesk}.entrypoints=http,https
        - traefik.http.routers.gjsx-${ID:-xdesk}.service=gjsx-${ID:-xdesk}
        - traefik.http.routers.gjsx-${ID:-xdesk}.tls=true
        - traefik.http.routers.gjsx-${ID:-xdesk}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.gjsx-${ID:-xdesk}.loadbalancer.server.port=8086
    networks:
      - traefik-net
      - edge
      - socket-proxy
    volumes:
      - project:/gjsx
    environment:
      C99_API_KEY: ${C99_API_KEY}

volumes:
  project:
    driver: local-persist
    driver_opts:
      mountpoint: ${project_mountpoint:-/home/administrator/app.xdesk}


networks:
  traefik-net:
    external: true
  edge:
    external: true
  socket-proxy:
    external: true
